require("buj.globals")
require("buj.settings")
require("buj.pkgs")
require("buj.lsp")
require("buj.kbs")
require("buj.gui")
require("buj.ts")
require("buj.git")
require("buj.tools")
if vim.g.neovide then require("buj.neovide") end
